name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
        with:
          node-version: 23
      - run: npm i
      - run: npm run lint
      